=== VanshikaJain06/Hotel-management-system/NewXMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="Travel">
<xs:complexType>
<xs:sequence>
<xs:element name="Hotel" maxOccurs="unbounded">
<xs:complexType>
<xs:sequence>
<xs:element name="Name" type="xs:string"></xs:element>
<xs:element name="Hotel_id" type="xs:integer"></xs:element>
<xs:element name="hotel_address" type="xs:string"></xs:element>
<xs:element name="contact_details" type="xs:integer"></xs:element>
<xs:element name="booking_date" type="xs:date"></xs:element>
<xs:element name="room_type" type="xs:string"></xs:element>
<xs:element name="services" type="xs:string"></xs:element>
<xs:element name="fare" type="xs:integer"></xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:simpleType name="fare">
<xs:restriction base="xs:integer">
<xs:mininclusive value="0"></xs:mininclusive>
<xs:maxInclusive value="10"></xs:maxInclusive>
</xs:restriction>
</xs:simpleType>



</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>

=== VanshikaJain06/Hotel-management-system/NewXMLSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<Travel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="NewXMLSchema.xsd">
  <Hotel>
    <Name>Name</Name>
    <Hotel_id>0</Hotel_id>
    <hotel_address>hotel_address</hotel_address>
    <contact_details>0</contact_details>
    <booking_date>2001-01-01</booking_date>
    <room_type>room_type</room_type>
    <services>services</services>
    <fare>0</fare>
  </Hotel>
</Travel>
